rethinkdb:
  image: dockerfile/rethinkdb
  ports:
   - "10402:8080"
   - "10403:28015"
   - "10404:29015"
server:
  build: .
  ports:
   - "10400:80"
   - "10401:81" # sharejs port
  links:
   - "rethinkdb"
  environment:
    NODE_ENV: production
    PORT: 80
  command: npm start
